backend:
  name: github
  repo: Weblightnovel/Website
  branch: main
  base_url: https://ajikameasane-eng.github.io/Weblightnovel
  auth_endpoint: /api/auth
  app_id: <Ov23liia3lC0iLCwaJqR>
  client_id: <Ov23liia3lC0iLCwaJqR>

media_folder: "assets/uploads"          
public_folder: "/assets/uploads"       

collections:
  - name: "stories"
    label: "Truyện"
    folder: "stories"
    create: true
    slug: "{{slug}}"                    
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Tác giả", name: "author", widget: "string", default: "Asane" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Ảnh bìa", name: "thumbnail", widget: "image" }
      - { label: "Mô tả ngắn", name: "description", widget: "text" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
