backend:
  name: github
  repo: ajikameasane-eng/Weblightnovel
  branch: main
  base_url: https://decap-oauth-bridge.onrender.com
  auth_endpoint: auth

media_folder: "assets/uploads"          
public_folder: "/assets/uploads"        

collections:
  - name: "stories"
    label: "Truyện"
    folder: "stories"
    create: true
    slug: "{{slug}}"                    
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Tác giả", name: "author", widget: "string", default: "Asane" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Ảnh bìa", name: "thumbnail", widget: "image" }
      - { label: "Mô tả ngắn", name: "description", widget: "text" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
