backend:
  name: github
  repo: ajikameasane-eng/Weblightnovel
  branch: main
  base_url: https://decap-oauth-bridge.onrender.com
  auth_endpoint: auth
  
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "stories"
    label: "Truyện"
    folder: "stories"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
