backend:
  name: github
  repo: <Weblightnovel>/<REPO>
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "stories"
    label: "Truyện"
    folder: "stories"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
