backend:
  name: github
  repo: Weblightnovel/Website
  branch: main
  base_url: https://ajikameasane-eng.github.io/Website
  auth_endpoint: /api/auth
  app_id: < Ov23liia3lC0iLCwaJqR>
  client_id: <Ov23liia3lC0iLCwaJqR>

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "stories"
    label: "Truyện"
    folder: "stories"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
